version: "3.9"

services:
  web:
    image: "reg.habales.de/gnol/gnol"
    ports:
      - "8666:9123"
    depends_on:
      - db
    volumes:
      - /home/falko/projekte/gnol/docker-compose-volumes/cache:/cache
      - /home/falko/projekte/gnol/docker-compose-volumes/files:/files

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=gnol
      - POSTGRES_PASSWORD=geheim!!
      - POSTGRES_DB=gnol
    ports:
      - '5432:5432'
    volumes:
      - gnol_db:/var/lib/postgresql/data

volumes:
  gnol_db: {}
